name: attendance_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fl_chart: ^0.30.0
  shared_preferences: ^2.0.5
  flutter_calendar_carousel: ^1.4.12
  lite_rolling_switch: ^0.1.1
  google_maps_flutter: ^2.0.2
  location: ^4.1.1
  file_picker: ^3.0.0
  http : ^0.13.0

#  qr: 1.3.0

#to reduce the size android and ios only
#  flutter_native_image: ^0.0.5

#  flutter_plugin_pdf_viewer: ^1.0.7
  native_pdf_view: ^4.0.1
#  avatar_glow:
  #use path provider ex for local app files instead of below
  ext_storage: ^1.0.3
  dio: ^4.0.0
  #commented for firebase storage web 19/3/21
  flutter_downloader: ^1.5.0
  permission_handler: 6.1.1
  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^0.3.4
  pdf: ^3.1.0
  qr_code_scanner: ^0.0.13
  google_fonts: ^2.0.0
#  data_tables: ^1.0.3


# for all platforms : android,ios,web

  google_sign_in: ^4.5.9
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1

  firebase: ^9.0.1

  firebase_messaging: ^9.1.0
  cloud_functions: ^1.0.2

#  firebase: ^7.3.0
#  firebase_auth_web:    #no need of this because other with same is available
#  firebase_storage: 3.1.6 #included web version in 7.0.0
#  firebase_core: ^0.4.4
#  cloud_firestore: 0.13.7
#  firebase_auth:     #included web in update


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
